/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.UserDAO;
import model.User;
import java.io.IOException;
import javax.swing.JOptionPane;
import util.FormUtils;
import util.HashPassword;

/**
 *
 * @author hieuk
 */
public class ChangePassword extends javax.swing.JFrame {

    /**
     * Creates new form RestPass
     */
    private UserDAO userDAO;
    private static User user;
    private boolean isHide1;
    private boolean isHide2;
    private boolean isHide3;
    public ChangePassword(User user) {
        initComponents();
        this.user = user;
        userDAO = new UserDAO();
        isHide1 = isHide2 = isHide3 = true;
        setResizable(false);
        setLocationRelativeTo(null);
         txtReNewPass.setEchoChar('●');
        txtPassword.setEchoChar('●');
        txtNewpass.setEchoChar('●');
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        txtNewpass = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtReNewPass = new javax.swing.JPasswordField();
        btnHide3 = new javax.swing.JButton();
        btnHide1 = new javax.swing.JButton();
        btnHide2 = new javax.swing.JButton();
        btnComfirm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ĐỔI MẬT KHẨU");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Mật khẩu hiện tại");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Mật khẩu mới");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Nhập lại mật khẩu");

        btnHide3.setForeground(new java.awt.Color(0, 102, 102));
        btnHide3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/hide-password-icon.png"))); // NOI18N
        btnHide3.setBorder(null);
        btnHide3.setBorderPainted(false);
        btnHide3.setContentAreaFilled(false);
        btnHide3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHide3ActionPerformed(evt);
            }
        });

        btnHide1.setForeground(new java.awt.Color(0, 102, 102));
        btnHide1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/hide-password-icon.png"))); // NOI18N
        btnHide1.setBorder(null);
        btnHide1.setBorderPainted(false);
        btnHide1.setContentAreaFilled(false);
        btnHide1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHide1ActionPerformed(evt);
            }
        });

        btnHide2.setForeground(new java.awt.Color(0, 102, 102));
        btnHide2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/hide-password-icon.png"))); // NOI18N
        btnHide2.setBorder(null);
        btnHide2.setBorderPainted(false);
        btnHide2.setContentAreaFilled(false);
        btnHide2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHide2ActionPerformed(evt);
            }
        });

        btnComfirm.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnComfirm.setText("XÁC NHẬN");
        btnComfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComfirmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtReNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnHide3))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNewpass, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnHide1)
                                    .addComponent(btnHide2)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(btnComfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnHide1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtNewpass, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHide2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txtReNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnHide3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnComfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHide3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHide3ActionPerformed
        // TODO add your handling code here:
        if(isHide3)
        {
            txtReNewPass.setEchoChar((char)0);
            btnHide3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/show-password-icon.png")));
        }
        else
        {
            btnHide3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/hide-password-icon.png")));
            txtReNewPass.setEchoChar('●');
        }
        isHide3 = !isHide3;
    }//GEN-LAST:event_btnHide3ActionPerformed

    private void btnHide1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHide1ActionPerformed
        // TODO add your handling code here:
        if(isHide1)
        {
            txtPassword.setEchoChar((char)0);
            btnHide1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/show-password-icon.png")));
        }
        else
        {
            btnHide1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/hide-password-icon.png")));
            txtPassword.setEchoChar('●');
        }
        isHide1 = !isHide1;
    }//GEN-LAST:event_btnHide1ActionPerformed

    private void btnHide2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHide2ActionPerformed
        // TODO add your handling code here:
        if(isHide2)
        {
            txtNewpass.setEchoChar((char)0);
            btnHide2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/show-password-icon.png")));
        }
        else
        {
            btnHide2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/hide-password-icon.png")));
            txtNewpass.setEchoChar('●');
        }
        isHide2 = !isHide2;
    }//GEN-LAST:event_btnHide2ActionPerformed

    private void btnComfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComfirmActionPerformed
        // TODO add your handling code here:
        if (!FormUtils.validateForm(getContentPane())) {
					JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin", "Error",
							JOptionPane.ERROR_MESSAGE);
					return;
				}

				String curPass = txtPassword.getText();
				String newPass = txtNewpass.getText();
				String rePass = txtReNewPass.getText();

				if (!user.getPassword().equals(HashPassword.hashPassword(curPass))) {
					JOptionPane.showMessageDialog(this, "Mật khẩu sai. Vui lòng thử lại.", "Error",
							JOptionPane.ERROR_MESSAGE);
					return;
				}

				if (newPass.equals(curPass)) {
					JOptionPane.showMessageDialog(this, "Mật khẩu mới không được trùng mật khẩu cũ.",
							"Error", JOptionPane.ERROR_MESSAGE);
					return;
				}

				if (!newPass.equals(rePass)) {
					JOptionPane.showMessageDialog(this, "Mật khẩu không khớp. Vui lòng nhập lại.",
							"Error", JOptionPane.ERROR_MESSAGE);
					return;
				}

				user.setPassword(HashPassword.hashPassword(newPass));
				try {
					userDAO.update(user);
					JOptionPane.showMessageDialog(this, "Thay đổi mật khẩu thành công.");
				} catch (ClassNotFoundException | IOException e1) {
					e1.printStackTrace();
				}

				dispose();			
    }//GEN-LAST:event_btnComfirmActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ChangePassword(user).setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComfirm;
    private javax.swing.JButton btnHide1;
    private javax.swing.JButton btnHide2;
    private javax.swing.JButton btnHide3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField txtNewpass;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JPasswordField txtReNewPass;
    // End of variables declaration//GEN-END:variables
}
